# Generated by Django 5.0.7 on 2024-07-20 12:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('info', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event_speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Familiya Ism Sharif')),
                ('address', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Familiya Ism Sharif')),
                ('info', ckeditor.fields.RichTextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/speaker/')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/sponsor/')),
            ],
        ),
    ]
