# Generated by Django 5.0.7 on 2024-07-23 07:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('info', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='event_speaker',
            name='address',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Manzil'),
        ),
    ]
