# Generated by Django 5.0.7 on 2024-07-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_about_conference_committee_organizers_and_sponsor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_conference',
        ),
        migrations.DeleteModel(
            name='Committee',
        ),
        migrations.DeleteModel(
            name='Organizers_and_sponsor',
        ),
    ]
