# Generated by Django 5.0.7 on 2024-07-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_delete_about_conference_delete_committee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/partner/')),
            ],
        ),
    ]
