# Generated by Django 5.0.7 on 2024-07-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_link', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('register_link', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
